# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35287aa0edac437db97c6bd2ac3d4e25b6ccd27698fc7b75e4b0f4a18af03d737d5aeb0df8dafc5da62c7fcab5fbe98f6e1a23aebc7ea97be3167c8c51e3ca29

test:
  secret_key_base: e9237341a1b45611e380d4daefbd29eb25b033c7c40e534b2cd2559ccc1de61fab769ed7fd0051e2f0c96c16a29343be3ee18946ba26a46a6797ee4320b75449

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
